export interface Utilisateur{
  id:number;
  adresse:string;
  adresseEmail:string;
  civilite:string;
  codePostale:string;
  identifiant:string;
  pays:string;
  nom:string;
  prenoms:string;
  role:string;
  motDePasse:string;
  dateNaissance:string;
  sex:string;
  b:boolean;
  telFix:string;
  telMobile:string;
  ville:string;
}
